version: '3'

services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    network_mode: "host"      
    restart: always
    environment:
      TZ: "Europe/Tallinn"      
    command:
      tunnel --no-autoupdate run --token $token
