version: '3.3'
services:
  # guacd
  guacd:
    container_name: guacamole-service
    image: guacamole/guacd:latest
    restart: unless-stopped
    volumes:
      - fonts:/usr/share/fonts/ 
      
  # guacamole tomcat9
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole-client
    environment:
      GUACD_HOSTNAME: guacamole-service
      GUACAMOLE_HOME : /etc/guacamole
      WEBAPP_CONTEXT: ROOT
    depends_on:
    - guacd
    - guacamole-mssql
    ports:
    - 8088:8080
    restart: unless-stopped
    volumes:
      - home:/etc/guacamole/  

#Microsoft SQL Express Server       
  guacamole-mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: guacamole-mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$mssql_password
    volumes:
      - sql:/var/opt/mssql/ 
      
#Persistent drive nfs map      
volumes:
  home:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/npu_cloud/guacamole/home
  sql:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/npu_cloud/guacamole/sql
  fonts:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/npu_cloud/guacamole/fonts
