---
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    volumes:
      - assets:/www/assets
    ports:
      - 8081:8080
volumes:
  assets:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/npu_cloud/homer