version: '3.3'
services:
    run:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=$msssql_password
        ports:
            - '1433:1433'
        image: mcr.microsoft.com/mssql/server:latest
        container_name: ms-sql
        volumes:
            - sql_home:/var/opt/mssql/
volumes:
  sql_home:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/npu_cloud/sql/