version: '3.1'
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    command:
       --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
