version: "3"
services:

  nextcloud-frontend:
    image: nextcloud:apache
    depends_on:
      - nextcloud-redis
      - nextcloud-elastic
      - nextcloud-postgres
    networks:
      - traefik-public
      - net
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud_db
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: nextcloud-postgres
    volumes:
      - /nextcloud/html:/var/www/html
      - /nextcloud/apps:/var/www/html/custom_apps
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/data:/var/www/html/data
      - /nextcloud/theme:/var/www/html/themes/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == kodu.docker]
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`cloud.npu.ee`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=cloud
      - traefik.http.services.portainer.loadbalancer.server.port=80  
      
  nextcloud-redis:
    image: redis:alpine
    networks:
      - traefik-public
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == kodu.docker]
        
  nextcloud-elastic:
    image: elasticsearch:7.17.7
    networks:
      - traefik-public
      - net
    environment:
      discovery.type : single-node
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == kodu.docker]
        
  nextcloud-cron:
    image: nextcloud:apache
    entrypoint: /cron.sh
    networks:
      - traefik-public
      - net
    depends_on:
      - nextcloud-frontend
      - nextcloud-redis
      - nextcloud-postgres
    volumes:
      - /nextcloud/html:/var/www/html
      - /nextcloud/apps:/var/www/html/custom_apps
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/data:/var/www/html/data
      - /nextcloud/theme:/var/www/html/themes/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == kodu.docker]
        
  nextcloud-postgres:
    image: postgres:14
    networks:
      - traefik-public
      - net
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud_db
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
       - /nextcloud/postgres:/data/postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == kodu.docker]      
networks:
  net:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1450
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
