version: "3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    environment:
      - TZ=Europe/Tallinn<timezone>
      - VERSION=latest
      - ADVERTISE_IP="https://plex.techhub.ee"
      - ALLOWED_NETWORKS="10.250.4.0/24"
      - HOSTNAME=$hostname
    volumes:
      - data:/config
      - media:/data
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    
#persistent drive nfs map      
volumes:
  media:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/media
  data:
    driver_opts:
      type: nfs 
      o: addr=10.250.4.4,rw,nolock
      device: :/npu_cloud/plex/data
