version: "3"
services:
  signal-backend:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-backend
    restart: unless-stopped
    environment:
      - MODE=normal
      - TZ="Europe/Tallinn"
    volumes:
      - /signal/backend:/home/.local/share/signal-cli
      
  signal-frontend:
    image: trafex/php-nginx:latest
    container_name: signal-frontend
    restart: unless-stopped
    environment:

      - TZ="Europe/Tallinn"    
    ports:
      - '8089:8080'
    depends_on:
    - signal-backend
    volumes:
      - /signal/frontend:/var/www/html
